# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1877a40f5c4287f7bf3c5f0bfa7b7d252c29a60fe43d30222ca64e7e638fc581c14699cef54de0c0c24b99b2a02f2e79b80e6d825eac8be8f15537f6e3babed6

test:
  secret_key_base: dbeb11643922836f1c36efb3ab06b70fd7f2b4fa0c327bd044670a33405053c7197f33e6a077d4183a47d63c029a03ff2ad36a8ce43921d883b4551897e845fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
